[build]
  base = "."
  command = "cd web && npm install && npm run build"
  publish = "web/out"

[build.environment]
  NODE_VERSION = "18"
  NODE_ENV = "production"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/restaurant/:id"
  to = "/restaurant/detail"
  status = 200

[[redirects]]
  from = "/news/:id"
  to = "/news/detail"
  status = 200

[[redirects]]
  from = "/reservation/:id"
  to = "/reservation/detail"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "*.map"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate" 